#!/bin/sh

cat <<EOT > /etc/nginx/reverse_fastcgi_params
# DO NOT EDIT, THIS FILE IS AUTOGENERATED!
set \$internetenabled "false";
EOT

/etc/init.d/nginx reload

############################################################
# APPLICAZIONE DATI WIFI SU OS LINUX
############################################################

# CLOSE STATION WIFI and
# START ACCESS POINT with SSID "wilc1000_SoftAP"
rmmod wilc_sdio
ln -sf /home/root/Start_Provision.sh /home/root/Start_Connection.sh
sh /home/root/Start_Connection.sh 

############################################################
# GENERAZIONE RESPONSE DEBUG
############################################################
echo "HTTP/1.0 200 OK"
echo "Content-type: text/plain"
echo ""
echo "fatto!"

reboot

