<?php
//ENGLISH-RUSSIAN
//login.php
define("_TITLELOGIN", "DKC E.STORAGE | LOGIN");
define("_HEADLOGIN", "DKC E.STORAGE LOGIN");
define("_USERNAME", "username");
define("_PASSWORD", "password");
define("_SUBMITLOGIN", "login");
define("_FORMMESSAGE1", "please insert your username");
define("_FORMMESSAGE2", "please insert your password");
define("_FORMMESSAGE3", "please check your credentials");
//change_password.php
define("_TITLECHANGEPASSWORD", "DKC E.STORAGE | CHANGE PASSWORD");
define("_HEADCHANGEPASSWORD", "CHANGE PASSWORD AT FIRST LOGIN");
define("_NEWPASSWORD1", "new password");
define("_NEWPASSWORD2", "confirm new password");
define("_NEWPASSWORDUPDATE", "UPDATE");
define("_NEWPASSWORDMESSAGE1", "please insert your new password");
define("_NEWPASSWORDMESSAGE2", "password must be at least 6 characters long");
define("_NEWPASSWORDMESSAGE3", "password must be differente than the old one");
define("_NEWPASSWORDMESSAGE4", "please confirm your new password");
define("_NEWPASSWORDMESSAGE5", "passwords do not match");
//menu
define("_MENUHOME", "HOME");
define("_MENULOGOUT", "LOGOUT");
define("_MENUOVERVIEW", "OVERVIEW");
define("_MENUINVERTER", "E.STORAGE");
define("_MENUTELEMETRY", "TELEMETRY");
define("_MENUTOPOLOGY", "TOPOLOGY");
define("_MENUSTATISTICS", "STATISTICS");
define("_MENUANALYTICS", "ANALYTICS");
define("_MENUSETTINGS", "SETTINGS");
define("_MENUPOWERMODE", "POWER MODE");
define("_MENUCONFIGURATIONS", "CONFIGURATIONS");
define("_MENUERRORS", "ERROR LOG");
define("_MENUNETWORK", "NETWORK");
define("_MENUCLOSE", "CLOSE");
//telemetry.php
define("_TITLETELEMETRY", "DKC E.STORAGE | TELEMETRY");
define("_HEADTELEMETRY", "TELEMETRY");
define("_INVERTER", "E.STORAGE");
define("_SOLAR", "solar");
define("_GRID", "grid");
define("_DOMESTIC", "domestic");
define("_STORAGE", "storage");
define("_VOLTAGE", "voltage");
define("_CURRENT", "current");
define("_CHARGE", "charge");
define("_INVERTERPOWER", "E.STORAGE power");
define("_INVERTERVOLT", "voltage");
define("_INVERTERCURR", "current");
define("_NETWORKFREQ", "frequency");
define("_POWERFACTOR", "power factor");
define("_CABINETTEMP", "cabinet temperature");
define("_HEATSINKTEMP", "heatsink temperature");
define("_INVERTERSTATUS", "E.STORAGE status");
define("_STORAGESTATUS", "storage status");
define("_MPPTPOWER1", "MPPT 1 power");
define("_MPPTPOWER2", "MPPT 2 power");
define("_MPPTVOLT1", "MPPT 1 voltage");
define("_MPPTVOLT2", "MPPT 2 voltage");
define("_MPPTCURR1", "MPPT 1 current");
define("_MPPTCURR2", "MPPT 2 current");
define("_RICEVALUE", "RICE value");
define("_PVTEMP", "PV temperature");
define("_PVSTAT", "PV status");
define("_BATTPOWER", "battery power");
define("_BATTVOLT", "voltage");
define("_BATTCURR", "current");
define("_BATTSOC", "state of charge");
define("_BATTSOH", "state of health");
define("_BATTCYCLENUM", "battery cycles");
define("_BATTMAXCHARGPOWER", "maximum charge power");
define("_BATTMAXDICHARGPOWER", "maximum discharge power");
define("_BATTSTAT", "battery status");
define("_3001COMMANDTITLE", "OPERATING PROFILE");
define("_3001COMMANDDESCRIPTION", "Select the operating mode of your E.STORAGE");
define("_3001COMMAND", "PLEASE SELECT");
define("_3001COMMANDMANUAL", "MANUAL");
define("_3001COMMANDECO", "ECO");
define("_3001COMMANDESS", "ESS");
define("_3001COMMANDGO", "Go");
define("_MODAL3001", "OPERATING PROFILE");
define("_MODAL3001ASK", "ARE YOU SURE YOU WANT TO CHANGE THE OPERATING PROFILE OF YOUR E.STORAGE?");
define("_MODAL3001NO", "NO");
define("_MODAL3001YES", "YES");
define("_3003COMMAND", "Set max power (W)");
define("_3003COMMANDGO", "GO");
define("_3000COMMANDTITLE", "Error reset");
define("_3000COMMANDDESCRIPTION", "Click to reset errors");
define("_3000COMMANDGO", "Go");
define("_MODAL3000", "ERROR RESET");
define("_MODAL3000ASK", "ARE YOU SURE YOU WANT TO RESET THE ERRORS?");
define("_MODAL3000NO", "NO");
define("_MODAL3000YES", "YES");
//system.php
define("_TITLESYSTEM", "DKC E.STORAGE | SYSTEM DATA");
define("_HEAD", "SYSTEM DATA");
define("_HEADDATA", "SYSTEM PARAMETERS");
define("_DATASHEET", "DOWNLOAD DATASHEET");
define('_MACAddr', 'MAC Address');
define('_Manufacturer', 'Manufacturer');
define('_NominalPower', 'Nominal Power');
define('_ModbusAddr', 'Modbus Address');
define('_LANIP', 'LAN IP Address');
define('_WLANIP', 'WLAN IP Address');
define('_DATE', 'Date');
define('_Language', 'Language');
define('_MQTTFreq', 'MQTT Frequency');
define('_SerialNum', 'Serial Number');
define('_SWVer', 'Software Version');
define('_MaxActPower', 'Max. Active Power');
define('_MaxAppPower', 'Max. Apparent Power');
define('_MaxReaPower', 'Max. Reactive Power');
define('_InverterConfig', 'E.STORAGE Configuration');
define('_MaxCurr', 'Max. Rated Current');
define('_MaxPF', 'Max. Power Factor');
define('_MinPF', 'Min. Power Factor');
define('_MaxNetVolt', 'Max. Network Voltage');
define('_MinNetVolt', 'Min. Network Voltage');
define('_MaxNetFreq', 'Max. Network Frequenc');
define('_MinNetFreq', 'Min. Network Frequency');
define('_MaxPVPower', 'Max. PV Power');
define('_MaxPVVolt', 'MAX. PV Voltage');
define('_MaxPVCurr', 'Max. PV Current');
define('_PVSeriesNum', 'Number of PV Series');
define('_PVStringNum', 'Number of PV Strings');
define('_BattNominalCappacity', 'Battery nominal Capacity');
define('_BattMaxChargPower', 'Battery Max. Charge Power');
define('_BattMaxDischarPower', 'Battery Max. Discharge Power');
define('_BattType', 'Battery Type');
define('_BattNumSeries', 'Number of Battery Series');
define('_BattStringNum', 'Number of Battery Strings');
define('_CellMaxVolt', 'Cell Max. Voltage');
define('_CellMaxVoltID', 'Cell Max. Voltage ID');
define('_CellMinVolt', 'Cell Min. Voltage');
define('_CellMinVoltID', 'Cell Min. Voltage ID');
define('_CellMaxTemp', 'Cell Max. Temp.');
define('_CellMaxTempID', 'Cell Max. Temp. ID');
define('_CellMinTemp', 'Cell Min. Temp.');
define('_CellMinTempID', 'Cell Min. Temp. ID');
define('_ModMaxVolt', 'Module Max. Voltage');
define('_ModMaxVoltID', 'Module Max. Voltage ID');
define('_ModMinVolt', 'Module Min. Voltage');
define('_ModMinVoltID', 'Module Min. Voltage ID');
define('_ModMaxTemp', 'Module Max. Temp.');
define('_ModMaxTempID', 'Module Max. Temp. ID');
define('_ModMinTemp', 'Module Min. Temp.');
define('_ModMinTempID', 'Module Min. Temp. ID');
//network.php
define("_TITLENETWORK", "DKC E.STORAGE | NETWORK SETTINGS");
define("_HEADNETWORK", "NETWORK SETTINGS");
define("_TITLENETWORKREBOOT", "DKC E.STORAGE | REBOOTING");
define("_NETWORKREBOOTING", "REBOOTING YOUR E.STORAGE");
define("_NETWORKREBOOTINGMESSAGE1", "Rebooting...");
define("_NETWORKREBOOTINGMESSAGE2", "If you have modified the network parameters, please change the address in the browser bar to find your E.STORAGE");
define("_NETWORKREBOOTINGMESSAGE3", "Register on our platform for all additional services");
define("_NETWORKREBOOTINGMESSAGE4", "When the LEDs are green, your E.STORAGE is ready");
define("_NETWORKREBOOTINGMESSAGE5", "You can close this window");
define("_PROVISIONINGWIFI", "WIRELESS NETWORK");
define("_PROVISIONINGSSIDNAME", "SSID name");
define("_PROVISIONINGPASSWORD", "password");
define("_PROVISIONINGWIFIDHCP", "wireless network DHCP");
define("_PROVISIONINGWIFISTATICIP", "wireless network static IP ADDRESS");
define("_PROVISIONINGWIFINETMASK", "wireless network NETMASK");
define("_PROVISIONINGWIFIGATEWAY", "wireless network GATEWAY");
define("_PROVISIONINGWIFIDNS", "wireless network DNS SERVER");
define("_PROVISIONINGNETWORK", "LAN NETWORK");
define("_PROVISIONINGNETWORKDHCP", "DHCP");
define("_PROVISIONINGNETWORKSTATICIP", "LAN network static IP ADDRESS");
define("_PROVISIONINGNETWORKNETMASK", "LAN network NETMASK");
define("_PROVISIONINGNETWORKGATEWAY", "LAN network GATEWAY");
define("_PROVISIONINGNETWORKDNS", "LAN network DNS SERVER");
define("_PROVISIONINGAPPLY", "APPLY");
define("_PROVISIONINGNONETWORK", "CONTINUE WITHOUT NETWORK");
define("_MODALNETWORK", "CONTINUE WITHOUT NETWORK");
define("_MODALWARNING", "ARE YOU SURE YOU WANT TO CONTINUE WITHOUT NETWORK?");
define("_MODALMESSAGEROW1", "--- WARNING ---");
define("_MODALMESSAGEROW2", "--- YOUR E.STORAGE WILL REBOOT ---");
define("_MODALNO", "NO");
define("_MODALYES", "YES");
define("_MODALMISSINGDATA", "MISSING DATA");
define("_MODALMISSINGDATAMESSAGE", "PLEASE FILL IN ALL MANDATORY FIELDS!");
//errors.php
define("_TITLEERRORS", "DKC E.STORAGE | ERROR LOG");
define("_HEADERRORS", "ERROR LOG");
define("_FILTERSEL", "FILTER SEVERITY");
define("_FILTERSELINFO", "INFO");
define("_FILTERSELERROR", "ERROR");
define("_FILTERSELWARNING", "WARNING");
define("_FILTERSELALL", "ALL");
define("_TABLEIDERRORS", "ID");
define("_TABLEDATEERRORS", "DATE");
define("_TABLEVALUEERRORS", "VALUE");
define("_TABLESEVERITYERRORS", "SEVERITY");
define("_TABLEPARAMETERERRORS", "PARAMETER");
define("_TABLENOERRORS", "NO ERROR FOUND");
//---------------------------------------------------
define("_TABLEDATA", "DATA");
define("_TABLEVALUE", "VALUE");
define("_TABLEACTION", "ACTION");
define("_TABLESERVERCOMM", "DATE");
define("_TABLEMACADDRESS", "MAC ADDRESS");
define("_TABLEMANUFACTURER", "MANUFACTURER");
define("_TABLEMAXPOWER", "E.CHARGER MAXIMUM POWER");
define("_TABLEMODBUSADDRESS", "MODBUS ADDRESS");
define("_TABLELANIPADDRESS", "LAN IP ADDRESS");
define("_TABLEWIFIPADDRESS", "Wi-Fi IP ADDRESS");
define("_TABLELANGUAGE", "LANGUAGE");
define("_TABLEREALTIMESAMPLING", "REAL-TIME SAMPLING");
define("_TABLEWBTYPE", "E.CHARGER TYPE");
define("_TABLESERIALNUMBER", "SERIAL NUMBER");
define("_TABLEFWVERSION", "FIRMWARE VERSION");
define("_TABLESWVERSION", "SOFTWARE VERSION");
define("_TABLERATEDPOWER", "RATED POWER");
define("_JAVASCRIPT0", "SINGLE-PHASE | CABLE");
define("_JAVASCRIPT1", "THREE-PHASE | CABLE");
define("_JAVASCRIPT2", "SINGLE-PHASE | PLUG");
define("_JAVASCRIPT3", "THREE-PHASE | PLUG");
define("_JAVASCRIPT4", "SINGLE-PHASE | CABLE | MID");
define("_JAVASCRIPT5", "THREE-PHASE | CABLE | MID");
define("_JAVASCRIPT6", "SINGLE-PHASE | PLUG | MID");
define("_JAVASCRIPT7", "THREE-PHASE | PLUG | MID");
define("_JAVASCRIPT8", "SINGLE-PHASE | CABLE | SIM");
define("_JAVASCRIPT9", "THREE-PHASE | CABLE | SIM");
define("_JAVASCRIPT10", "SINGLE-PHASE | PLUG | SIM");
define("_JAVASCRIPT11", "THREE-PHASE | PLUG | SIM");
define("_JAVASCRIPT12", "SINGLE-PHASE | CABLE | MID | SIM");
define("_JAVASCRIPT13", "THREE-PHASE | CABLE | MID | SIM");
define("_JAVASCRIPT14", "SINGLE-PHASE | PLUG | MID | SIM");
define("_JAVASCRIPT15", "THREE-PHASE | PLUG | MID | SIM");
//---------------------------------------------------
define("_TABLEDATATELEMETRY", "DATA");
define("_TABLEVALUETELEMETRY", "VALUE");
define("_TABLEPOWERMETERTELEMETRY", "POWER METER");
define("_TABLEINSTANTPOWERTELEMETRY", "INSTANT POWER");
define("_TABLERPHASECURRENTRTELEMETRY", "R PHASE CURRENT");
define("_TABLESPHASECURRENTRTELEMETRY", "S PHASE CURRENT");
define("_TABLETPHASECURRENTRTELEMETRY", "T PHASE CURRENT");
define("_TABLEVOLTAGETELEMETRY", "VOLTAGE");
define("_TABLEACTIVEUSERTELEMETRY", "ACTIVE USER");
define("_TABLEACTIVEUSERTELEMETRYNOBODY", "NOBODY");
define("_TABLECHARGINGTIMETELEMETRY", "CHARGING TIME");
define("_TABLESUPPLIEDENERGYTELEMETRY", "SUPPLIED ENERGY");
define("_TABLETEMPERATURETELEMETRY", "TEMPERATURE");
define("_TABLEECHARGERSTATUSTELEMETRY", "E.CHARGER STATUS");
define("_ECHARGERSTATUSREADY", "READY");
define("_ECHARGERSTATUSCONNECTED", "CONNECTED");
define("_ECHARGERSTATUSCHARGING", "CHARGING");
define("_ECHARGERSTATUSLOCKED", "LOCKED");
define("_ECHARGERSTATUSERROR", "ERROR");
//cards.php
define("_TITLECARDS", "DKC E.CHARGER | RFID CARDS");
define("_HEADCARDS", "RFID CARDS");
define("_ADDBUTTONHELPCARDS", "click and swipe your RFID card on the reader");
define("_ADDBUTTONCARDS", "Add a new RFID card");
define("_TABLEIDCARDS", "ID");
define("_TABLERFIDCARDNOCARDS", "RFID CARD NUMBER");
define("_TABLECARDNAMECARDS", "CARD NAME");
define("_TABLECREATIONDATECARDS", "CREATION DATE");
define("_TABLEFUNCTIONSCARDS", "FUNCTIONS");
define("_TABLEBUTTONMODIFYNAMECARDS", "MODIFY CARD'S NAME");
define("_TABLEBUTTONDELETECARDCARDS", "DELETE CARD");
define("_TABLENOCARDSCARDS", "NO CARD FOUND");
define("_MODALMODIFYNAMECARDS", "MODIFY CARD'S NAME");
define("_MODALOLDNAMECARDS", "OLD NAME:");
define("_MODALNEWNAMECARDS", "NEW NAME:");
define("_MODALOKCARDS", "OK");
define("_MODALDELETECARDCARDS", "DELETE CARDS");
define("_MODALDELETECARDWARNINGCARDS", "ARE YOU SURE YOU WANT TO DELETE THIS RFID CARD?");
define("_MODALNOCARDS", "NO");
define("_MODALYESCARDS", "YES");
define("_MODALTITLEMODIFYCARDCARDS", "change name for RFID card number: ");
define("_MODALTITLEDELETECARDCARDS", "delete RIFD card number: ");
define("_TOASTCOMMANDKO", "ERROR - COMMAND NOT EXECUTED");
define("_TOASTCOMMANDOK", "COMMAND EXECUTED");
define("_TOASTCOMMANDNOTAVAILABLE", "COMMAND NOT AVAILABLE");
define("_TOASTCOMMANDSKIPSERIAL", "COMMAND EXECUTED - SKIP SERIAL");
define("_TOASTCOMMANDERROR", "ERROR");
//transactions.php
define("_TITLETRANSACTIONS", "DKC E.CHARGER | TRANSACTIONS");
define("_HEADTRANSACTIONS", "TRANSACTIONS");
define("_TABLEIDTRANSACTIONS", "ID");
define("_TABLEDATETRANSACTIONS", "DATE");
define("_TABLECARDNOTRANSACTIONS", "RFID CARD NUMBER");
define("_TABLECARDNAMETRANSACTIONS", "CARD NAME");
define("_TABLEECHARGERSTATUSTRANSACTIONS", "E.CHARGER STATUS");
define("_TABLESTARTTRANSACTIONS", "START TIME");
define("_TABLEENDTRANSACTIONS", "END TIME");
define("_TABLECHARGINGTIMETRANSACTIONS", "CHARGING TIME");
define("_TABLESUPPLIEDENERGYTRANSACTIONS", "SUPPLIED ENERGY");
define("_TABLEERRORSTRANSACTIONS", "ERRORS");
define("_TABLENOTRANSACTIONTRANSACTIONS", "NO TRANSACTION FOUND");
define("_TABLESTATUSREADYTRANSACTIONS", "READY");
define("_TABLESTATUSCONNECTEDTRANSACTIONS", "CONNECTED");
define("_TABLESTATUSCHARGINGTRNSACTIONS", "CHARGING");
define("_TABLESTATUSLOCKEDTRANSACTIONS", "LOCKED");
define("_TABLESTATUSERRORTRANSACTIONS", "ERROR");
//commands.php
define("_TITLECOMMANDS", "DKC E.CHARGER | COMMANDS");
define("_HEADCOMMANDS", "COMMANDS");
define("_TABLEPARAMETERCOMMANDS", "PARAMETER");
define("_TABLEVALUECOMMANDS", "VALUE / ACTION");
define("_TABLEHELPCOMMANDS", "HELP");
define("_TABLE3000COMMANDS", "OPERATE E.CHARGER");
define("_TABLE3000SELCOMMANDS", "PLEASE SELECT");
define("_TABLE3000STARTCOMMANDS", "Start");
define("_TABLE3000STOPCOMMANDS", "Stop");
define("_TABLEAPPLYCOMMANDS", "APPLY");
define("_TABLEINSERTVALUECOMMANDS", "PLEASE INSERT A VALUE");
define("_TABLE3003COMMANDS", "SET MAX POWER (W)");
define("_TABLE3006COMMANDS", "ENABLE MEASURE FOR LOAD BALANCING");
define("_TABLE3006SELCOMMANDS", "PLEASE SELECT");
define("_TABLE3006DISABLECOMMANDS", "DISABLE");
define("_TABLE3006ENABLECOMMANDS", "ENABLE");
define("_TABLE3007COMMANDS", "RFID CARD READER");
define("_TABLE3007SELCOMMANDS", "PLEASE SELECT");
define("_TABLE3007DISABLECOMMANDS", "DISABLE");
define("_TABLE3007ENABLECOMMANDS", "ENABLE");
define("_TABLE3009COMMANDS", "ENABLE / DISABLE OCPP 1.6");
define("_TABLE3009SELCOMMANDS", "PLEASE SELECT");
define("_TABLE3009DISABLECOMMANDS", "DISABLE");
define("_TABLE3009ENABLECOMMANDS", "ENABLE");
define("_TABLE3010COMMANDS", "ENABLE / DISABLE MODBUS");
define("_TABLE3010SELCOMMANDS", "PLEASE SELECT");
define("_TABLE3010DISABLECOMMANDS", "DISABLE");
define("_TABLE3010ENABLECOMMANDS", "ENABLE");
define("_TABLE3012COMMANDS", "SOFTWARE UPDATE");
define("_TABLE3013COMMANDS", "SEND E.CHARGER DATA TO CLOUD");
define("_TABLE3014COMMANDS", "ERROR RESET");
define("_TABLE3017COMMANDS", "SYSTEM REBOOT");
define("_TABLE3017SELCOMMANDS", "PLEASE SELECT");
define("_TABLE3017REBOOTCOMMANDS", "REBOOT");
define("_TABLE3017RESTARTCOMMANDS", "SOFT-RESTART");
define("_TOASTCOMMANDNOUPDATE", "NO UPDATE AVAILABLE");
define("_MODALSWUPDATECOMMANDS", "SOFTWARE UPDATE");
define("_MODALSWUPDATEWARNINGCOMMANDS", "ARE YOU SURE YOU WANT TO UPDATE YOUR E.CHARGER?");
define("_MODALNOCOMMANDS", "NO");
define("_MODALYESCOMMANDS", "YES");
define("_HELPOPERATECOMMANDS", "START / STOP CHARGE");
define("_HELPMAXPOWERCOMMANDS", "SET MAXIMUM LOAD");
define("_HELPFIXEDPOWERCOMMANDS", "SET FIXED POWER MODE AND DISABLE THE POWER METER DYNAMIC MANAGEMENT");
define("_HELPRFIDREADERCOMMANDS", "ENABLE OR DISABLE RFID CARD READER");
define("_HELPOCPPCOMMANDS", "ENABLE OR DISABLE OCPP PROTOCOL");
define("_HELPMODBUSCOMMANDS", "ENABLE OR DISABLE MODBUS PROTOCOL");
define("_HELPSWUPDATECOMMANDS", "UPDATE E.CHARGER SOFTWARE (INTERNET CONNECTION REQUIRED)");
define("_HELPSENDCLOUDCOMMANDS", "MANUALLY UPDATE CLOUD WITH LATEST E.CHARGER INFO");
define("_HELPERRORCOMMANDS", "RESTORE E.CHARGER STATUS");
define("_HELPREBOOT", "REBOOT=reboot your E.CHARGER | SOFT-RESTART=reboot only primary services");
define("_ENABLED", "ENABLED");
define("_DISABLED", "DISABLED");
define("_NOTAVAILABLE", "---");
define("_ENABLE", "ENABLE");
define("_DISABLE", "DISABLE");
//configurations.php
define("_TITLECONFIGURATIONS", "DKC E.CHARGER | CONFIGURATIONS");
define("_HEADCONFIGURATIONS", "CONFIGURATIONS");
define("_TABLEUSER", "User configuration parameters");
define("_TABLEOCPP", "OCPP communication configuration parameters");
define("_TABLEINST", "Installation parameters");
define("_TABLENAMECONFIGURATIONS", "NAME");
define("_TABLEVALUECONFIGURATIONS", "VALUE");
define("_TABLEUOMCONFIGURATIONS", "UoM");
define("_TABLEMODIFYCONFIGURATIONS", "MODIFY / UPDATE");
define("_TABLEHELPCONFIGURATIONS", "HELP");
define("_TABLESELCONFIGURATIONS", "PLEASE SELECT");
define("_TABLETRUECONFIGURATIONS", "TRUE");
define("_TABLEFALSECONFIGURATIONS", "FALSE");
define("_TABLEITCONFIGURATIONS", "ITALIANO");
define("_TABLEENCONFIGURATIONS", "ENGLISH");
define("_TABLERUCONFIGURATIONS", "РУССКИЙ");
define("_TABLEUPDATECONFIGURATIONS", "UPDATE");
define("_TABLENOCONFIGURATIONS", "NO CONFIGURATION FOUND");
define("_TABLECONF1", "Minimum available power");
define("_TABLECONF2", "RFID card validity timeout");
define("_TABLECONF3", "Button pressed for a long time");
define("_TABLECONF4", "Button pressed for a very long time");
define("_TABLECONF5", "Minimum available current");
define("_TABLECONF6", "Manufacturer name");
define("_TABLECONF7", "MODBUS address");
define("_TABLECONF8", "Installation date");
define("_TABLECONF9", "Language");
define("_TABLECONF10", "Time between polling realtime mqtt data");
define("_TABLECONF11", "Wallbox serial number");
define("_TABLECONF12", "Maximum temperature limit");
define("_TABLECONF13", "Minimum temperature limit");
define("_TABLECONF14", "Minimum voltage limit");
define("_TABLECONF15", "Maximum voltage limit");
define("_TABLECONF16", "E.CHARGER connection timeout");
define("_TABLECONF17", "OCPP server IP address");
define("_TABLECONF18", "OCPP server port");
define("_TABLECONF19", "OCPP server URL");
define("_TABLECONF20", "Internal MID energy meter");
define("_TABLECONF21", "External power meter");
define("_TABLECONF22", "Inverter presence");
define("_TABLECONF23", "Charge paused at startup");
define("_TABLECONF24", "LED intensity");
define("_TABLECONF25", "Timezone");
define("_TABLECONF26", "Home maximum power");
define("_TABLECONFGEN", "Missing parameter");
//index_provisioning.php
define("_SELECTWIFINETWORK", "PLEASE CHOOSE A WIRELESS NETWORK");
define("_FINDWIFINETWORK", "find available Wi-Fi networks");
?>