<?php
//ITALIANO
//login.php
define("_TITLELOGIN", "DKC E.STORAGE | LOGIN");
define("_HEADLOGIN", "DKC E.STORAGE LOGIN");
define("_USERNAME", "nome utente");
define("_PASSWORD", "password");
define("_SUBMITLOGIN", "login");
define("_FORMMESSAGE1", "inserisci il tuo nome utente");
define("_FORMMESSAGE2", "inserisci la tua password");
define("_FORMMESSAGE3", "controlla le credenziali");
//change_password.php
define("_TITLECHANGEPASSWORD", "DKC E.STORAGE | MODIFICA PASSWORD");
define("_HEADCHANGEPASSWORD", "MODIFICA LA PASSWORD AL PRIMO LOGIN");
define("_NEWPASSWORD1", "nuova password");
define("_NEWPASSWORD2", "conferma nuova password");
define("_NEWPASSWORDUPDATE", "AGGIORNA");
define("_NEWPASSWORDMESSAGE1", "inserisci la tua nuova password");
define("_NEWPASSWORDMESSAGE2", "la password deve contenere almeno 6 caratteri");
define("_NEWPASSWORDMESSAGE3", "la password deve essere diversa da quella usata in precedenza");
define("_NEWPASSWORDMESSAGE4", "conferma la tua nuova password");
define("_NEWPASSWORDMESSAGE5", "le password non corrispondono");
//menu
define("_MENUHOME", "HOME");
define("_MENULOGOUT", "LOGOUT");
define("_MENUOVERVIEW", "OVERVIEW");
define("_MENUINVERTER", "E.STORAGE");
define("_MENUTELEMETRY", "TELEMETRIA");
define("_MENUTOPOLOGY", "TOPOLOGIA");
define("_MENUSTATISTICS", "STATISTICHE");
define("_MENUANALYTICS", "ANALISI");
define("_MENUSETTINGS", "IMPOSTAZIONI");
define("_MENUPOWERMODE", "MODALITA' POTENZA");
define("_MENUCONFIGURATIONS", "CONFIGURAZIONI");
define("_MENUERRORS", "ERROR LOG");
define("_MENUNETWORK", "RETE");
define("_MENUCLOSE", "CHIUDI");
//telemetry.php
define("_TITLETELEMETRY", "DKC E.STORAGE | TELEMETRIA");
define("_HEADTELEMETRY", "TELEMETRIA");
define("_INVERTER", "E.STORAGE");
define("_SOLAR", "solare");
define("_GRID", "rete");
define("_DOMESTIC", "domestico");
define("_STORAGE", "accumulo");
define("_VOLTAGE", "tensione");
define("_CURRENT", "corrente");
define("_CHARGE", "carica");
define("_INVERTERPOWER", "potenza E.STORAGE");
define("_INVERTERVOLT", "tensione");
define("_INVERTERCURR", "corrente");
define("_NETWORKFREQ", "frequenza");
define("_POWERFACTOR", "fattore di potenza");
define("_CABINETTEMP", "temperatura cabinet");
define("_HEATSINKTEMP", "temperatura dissipatore");
define("_INVERTERSTATUS", "stato E.STORAGE");
define("_STORAGESTATUS", "stato accumulo");
define("_MPPTPOWER1", "potenza MPPT 1");
define("_MPPTPOWER2", "potenza MPPT 2");
define("_MPPTVOLT1", "tensione MPPT 1");
define("_MPPTVOLT2", "tensione MPPT 2");
define("_MPPTCURR1", "corrente MPPT 1");
define("_MPPTCURR2", "corrente MPPT 2");
define("_RICEVALUE", "valore RICE");
define("_PVTEMP", "temperatura FV");
define("_PVSTAT", "stato FV");
define("_BATTPOWER", "potenza batterie");
define("_BATTVOLT", "tensione");
define("_BATTCURR", "corrente");
define("_BATTSOC", "stato di carica");
define("_BATTSOH", "stato di salute");
define("_BATTCYCLENUM", "cicli batterie");
define("_BATTMAXCHARGPOWER", "potenza massima di carica");
define("_BATTMAXDICHARGPOWER", "potenza massima di scarica");
define("_BATTSTAT", "stato batterie");
define("_3001COMMANDTITLE", "PROFILO OPERATIVO");
define("_3001COMMANDDESCRIPTION", "Seleziona il profilo operativo per il tuo E.STORAGE");
define("_3001COMMAND", "SELEZIONA");
define("_3001COMMANDMANUAL", "MANUALE");
define("_3001COMMANDECO", "ECO");
define("_3001COMMANDESS", "ESS");
define("_3001COMMANDGO", "Vai");
define("_MODAL3001", "PROFILO OPERATIVO");
define("_MODAL3001ASK", "SEI SICURO DI VOLER MODIFICARE IL PROFILO OPERATIVO DEL TUO E.STORAGE?");
define("_MODAL3001NO", "NO");
define("_MODAL3001YES", "SI");
define("_3003COMMAND", "Imposta potenza massima (W)");
define("_3003COMMANDGO", "VAI");
define("_3000COMMANDTITLE", "Reset errori");
define("_3000COMMANDDESCRIPTION", "Clicca per azzerare gli errori");
define("_3000COMMANDGO", "Vai");
define("_MODAL3000", "RESET ERRORI");
define("_MODAL3000ASK", "SEI SICURO DI VOLER AZZERARE GLI ERRORI?");
define("_MODAL3000NO", "NO");
define("_MODAL3000YES", "SI");
//system.php
define("_TITLESYSTEM", "DKC E.STORAGE | DATI DI SISTEMA");
define("_HEAD", "DATI DI SISTEMA");
define("_HEADDATA", "PARAMETRI DI SISTEMA");
define("_DATASHEET", "SCARICA LA SCHEDA TECNICA");
define('_MACAddr', 'MAC Address');
define('_Manufacturer', 'Produttore');
define('_NominalPower', 'Potenza nominale');
define('_ModbusAddr', 'Indirizzo MODBUS');
define('_LANIP', 'Indirizzo IP LAN');
define('_WLANIP', 'Indirizzo IP Wi-Fi');
define('_DATE', 'Data');
define('_Language', 'Lingua');
define('_MQTTFreq', 'Frequenza dati MQTT');
define('_SerialNum', 'Numero seriale');
define('_SWVer', 'Versione software');
define('_MaxActPower', 'Potenza attiva massima');
define('_MaxAppPower', 'Potenza apparente massima');
define('_MaxReaPower', 'Potenza reattiva massima');
define('_InverterConfig', 'Configurazione E.STORAGE');
define('_MaxCurr', 'Corrente nominale massima');
define('_MaxPF', 'Fattore di potenza massima');
define('_MinPF', 'Fattore di potenza minima');
define('_MaxNetVolt', 'Tensione di rete massima');
define('_MinNetVolt', 'Tensione di rete minima');
define('_MaxNetFreq', 'Frequenza di rete massima');
define('_MinNetFreq', 'Frequenza di rete minima');
define('_MaxPVPower', 'Potenza massima FV');
define('_MaxPVVolt', 'Tensione massima FV');
define('_MaxPVCurr', 'Corrente massima FV');
define('_PVSeriesNum', 'Numero di serie FV');
define('_PVStringNum', 'Numero di stringhe FV');
define('_BattNominalCappacity', 'Capacità nominale batterie');
define('_BattMaxChargPower', 'Potenza massima di carica batterie');
define('_BattMaxDischarPower', 'Potenza massima di scarica batterie');
define('_BattType', 'Tipo di batterie');
define('_BattNumSeries', 'Numero di serie batterie');
define('_BattStringNum', 'Numero di stringhe batterie');
define('_CellMaxVolt', 'Tensione massima celle');
define('_CellMaxVoltID', 'ID tensione massima celle');
define('_CellMinVolt', 'Tensione minima celle');
define('_CellMinVoltID', 'ID tensione minima celle');
define('_CellMaxTemp', 'Temperatura massima celle');
define('_CellMaxTempID', 'ID temperatura massima celle');
define('_CellMinTemp', 'Temperatura minima celle');
define('_CellMinTempID', 'ID temperatura minima celle');
define('_ModMaxVolt', 'Tensione massima moduli');
define('_ModMaxVoltID', 'ID tensione massima moduli');
define('_ModMinVolt', 'Tensione minima moduli');
define('_ModMinVoltID', 'ID tensione minima moduli');
define('_ModMaxTemp', 'Temperatura massima moduli');
define('_ModMaxTempID', 'ID temperatura massima moduli');
define('_ModMinTemp', 'Temperatura minima moduli');
define('_ModMinTempID', 'ID temperatura minima moduli');
//network.php
define("_TITLENETWORK", "DKC E.STORAGE | IMPOSTAZIONI RETE");
define("_HEADNETWORK", "IMPOSTAZIONI RETE");
define("_TITLENETWORKREBOOT", "DKC E.STORAGE | RIAVVIO");
define("_NETWORKREBOOTING", "IL TUO E.STORAGE SI STA RIAVVIANDO");
define("_NETWORKREBOOTINGMESSAGE1", "Riavvio...");
define("_NETWORKREBOOTINGMESSAGE2", "Se hai modificato i parametri di rete, cambia l'indirizzo nella barra del browser per trovare il tuo E.STORAGE");
define("_NETWORKREBOOTINGMESSAGE3", "Registrati sulla nostra piattaforma per tutti i servizi aggiuntivi");
define("_NETWORKREBOOTINGMESSAGE4", "Quando i LED sono verdi, il tuo E.STORAGE e' pronto");
define("_NETWORKREBOOTINGMESSAGE5", "Puoi chiudere questa finestra");
define("_PROVISIONINGWIFI", "RETE WIRELESS");
define("_PROVISIONINGSSIDNAME", "nome SSID");
define("_PROVISIONINGPASSWORD", "password");
define("_PROVISIONINGWIFIDHCP", "DHCP rete wireless");
define("_PROVISIONINGWIFISTATICIP", "INDIRIZZO IP statico rete wireless");
define("_PROVISIONINGWIFINETMASK", "NETMASK rete wireless");
define("_PROVISIONINGWIFIGATEWAY", "GATEWAY rete wireless");
define("_PROVISIONINGWIFIDNS", "SERVER DNS rete wireless");
define("_PROVISIONINGNETWORK", "RETE LAN");
define("_PROVISIONINGNETWORKDHCP", "DHCP");
define("_PROVISIONINGNETWORKSTATICIP", "INDIRIZZO IP statico rete LAN");
define("_PROVISIONINGNETWORKNETMASK", "NETMASK rete LAN");
define("_PROVISIONINGNETWORKGATEWAY", "GATEWAY rete LAN");
define("_PROVISIONINGNETWORKDNS", "SERVER DNS rete LAN");
define("_PROVISIONINGAPPLY", "APPLICA");
define("_PROVISIONINGNONETWORK", "CONTINUA SENZA RETE");
define("_MODALNETWORK", "CONTINUA SENZA RETE");
define("_MODALWARNING", "SEI SICURO DI CONTINUARE SENZA RETE?");
define("_MODALMESSAGEROW1", "--- ATTENZIONE ---");
define("_MODALMESSAGEROW2", "--- IL TUO E.STORAGE SI RIAVVIERA' ---");
define("_MODALNO", "NO");
define("_MODALYES", "SI");
define("_MODALMISSINGDATA", "DATI MANCANTI");
define("_MODALMISSINGDATAMESSAGE", "INSERISCI TUTTI I DATI OBBLIGATORI!");
//errors.php
define("_TITLEERRORS", "DKC E.STORAGE | ERROR LOG");
define("_HEADERRORS", "ERROR LOG");
define("_FILTERSEL", "FILTRA SEVERITA'");
define("_FILTERSELINFO", "INFO");
define("_FILTERSELERROR", "ERROR");
define("_FILTERSELWARNING", "WARNING");
define("_FILTERSELALL", "TUTTI");
define("_TABLEIDERRORS", "ID");
define("_TABLEDATEERRORS", "DATA");
define("_TABLEVALUEERRORS", "VALORE");
define("_TABLESEVERITYERRORS", "SEVERITA'");
define("_TABLEPARAMETERERRORS", "PARAMETRO");
define("_TABLENOERRORS", "NESSUN ERRORE TROVATO");
//---------------------------------------------------
define("_TABLEDATA", "DATO");
define("_TABLEVALUE", "VALORE");
define("_TABLEACTION", "AZIONE");
define("_TABLESERVERCOMM", "DATA");
define("_TABLEMACADDRESS", "MAC ADDRESS");
define("_TABLEMANUFACTURER", "PRODUTTORE");
define("_TABLEMAXPOWER", "POTENZA MASSIMA E.CHARGER");
define("_TABLEMODBUSADDRESS", "INDIRIZZO MODBUS");
define("_TABLELANIPADDRESS", "INDIRIZZO IP LAN");
define("_TABLEWIFIPADDRESS", "INDIRIZZO IP Wi-Fi");
define("_TABLELANGUAGE", "LINGUA");
define("_TABLEREALTIMESAMPLING", "INTERVALLO DATI REAL-TIME");
define("_TABLEWBTYPE", "TIPO E.CHARGER");
define("_TABLESERIALNUMBER", "NUMERO DI SERIE");
define("_TABLEFWVERSION", "VERSIONE FIRMWARE");
define("_TABLESWVERSION", "VERSIONE SOFTWARE");
define("_TABLERATEDPOWER", "POTENZA DI TARGA");
define("_JAVASCRIPT0", "MONOFASE | CAVO");
define("_JAVASCRIPT1", "TRIFASE | CAVO");
define("_JAVASCRIPT2", "MONOFASE | PRESA");
define("_JAVASCRIPT3", "TRIFASE | PRESA");
define("_JAVASCRIPT4", "MONOFASE | CAVO | MID");
define("_JAVASCRIPT5", "TRIFASE | CAVO | MID");
define("_JAVASCRIPT6", "MONOFASE | PRESA | MID");
define("_JAVASCRIPT7", "TRIFASE | PRESA | MID");
define("_JAVASCRIPT8", "MONOFASE | CAVO | SIM");
define("_JAVASCRIPT9", "TRIFASE | CAVO | SIM");
define("_JAVASCRIPT10", "MONOFASE | PRESA | SIM");
define("_JAVASCRIPT11", "TRIFASE | PRESA | SIM");
define("_JAVASCRIPT12", "MONOFASE | CAVO | MID | SIM");
define("_JAVASCRIPT13", "TRIFASE | CAVO | MID | SIM");
define("_JAVASCRIPT14", "MONOFASE | PRESA | MID | SIM");
define("_JAVASCRIPT15", "TRIFASE | PRESA | MID | SIM");
//---------------------------------------------------
define("_TABLEDATATELEMETRY", "DATO");
define("_TABLEVALUETELEMETRY", "VALORE");
define("_TABLEPOWERMETERTELEMETRY", "POWER METER");
define("_TABLEINSTANTPOWERTELEMETRY", "POTENZA ISTANTANEA");
define("_TABLERPHASECURRENTRTELEMETRY", "CORRENTE FASE R");
define("_TABLESPHASECURRENTRTELEMETRY", "CORRENTE FASE S");
define("_TABLETPHASECURRENTRTELEMETRY", "CORRENTE FASE T");
define("_TABLEVOLTAGETELEMETRY", "TENSIONE");
define("_TABLEACTIVEUSERTELEMETRY", "UTENTE ATTIVO");
define("_TABLEACTIVEUSERTELEMETRYNOBODY", "NESSUNO");
define("_TABLECHARGINGTIMETELEMETRY", "TEMPO DI RICARICA");
define("_TABLESUPPLIEDENERGYTELEMETRY", "ENERGIA EROGATA");
define("_TABLETEMPERATURETELEMETRY", "TEMPERATURA");
define("_TABLEECHARGERSTATUSTELEMETRY", "STATO E.CHARGER");
define("_ECHARGERSTATUSREADY", "PRONTO");
define("_ECHARGERSTATUSCONNECTED", "CONNESSO");
define("_ECHARGERSTATUSCHARGING", "IN CARICA");
define("_ECHARGERSTATUSLOCKED", "LOCKED");
define("_ECHARGERSTATUSERROR", "ERRORE");
//cards.php
define("_TITLECARDS", "DKC E.CHARGER | CARTE RFID");
define("_HEADCARDS", "CARTE RFID");
define("_ADDBUTTONHELPCARDS", "clicca e passa la tua carta RFID sul lettore");
define("_ADDBUTTONCARDS", "Aggiungi una nuova carta RFID");
define("_TABLEIDCARDS", "ID");
define("_TABLERFIDCARDNOCARDS", "NUMERO CARTA RFID");
define("_TABLECARDNAMECARDS", "NOME CARTA RFID");
define("_TABLECREATIONDATECARDS", "DATA DI CREAZIONE");
define("_TABLEFUNCTIONSCARDS", "FUNZIONI");
define("_TABLEBUTTONMODIFYNAMECARDS", "MODIFICA NOME CARTA");
define("_TABLEBUTTONDELETECARDCARDS", "ELIMINA CARTA");
define("_TABLENOCARDSCARDS", "NESSUNA CARTA RFID TROVATA");
define("_MODALMODIFYNAMECARDS", "MODIFICA NOME CARTA");
define("_MODALOLDNAMECARDS", "VECCHIO NOME:");
define("_MODALNEWNAMECARDS", "NUOVO NOME:");
define("_MODALOKCARDS", "OK");
define("_MODALDELETECARDCARDS", "ELIMINA CARTA");
define("_MODALDELETECARDWARNINGCARDS", "SEI SICURO DI VOLER ELIMINARE QUESTA CARTA RFID?");
define("_MODALNOCARDS", "NO");
define("_MODALYESCARDS", "SI");
define("_MODALTITLEMODIFYCARDCARDS", "modifica il nome per la carta RFID numero: ");
define("_MODALTITLEDELETECARDCARDS", "elimina la carta RIFD numero: ");
define("_TOASTCOMMANDKO", "ERRORE - COMANDO NON ESEGUITO");
define("_TOASTCOMMANDOK", "COMANDO ESEGUITO");
define("_TOASTCOMMANDNOTAVAILABLE", "COMANDO NON DISPONIBILE");
define("_TOASTCOMMANDSKIPSERIAL", "COMANDO ESEGUITO - SKIP SERIAL");
define("_TOASTCOMMANDERROR", "ERRORE");
//transactions.php
define("_TITLETRANSACTIONS", "DKC E.CHARGER | TRANSAZIONI");
define("_HEADTRANSACTIONS", "TRANSAZIONI");
define("_TABLEIDTRANSACTIONS", "ID");
define("_TABLEDATETRANSACTIONS", "DATA");
define("_TABLECARDNOTRANSACTIONS", "NUMERO CARTA RFID");
define("_TABLECARDNAMETRANSACTIONS", "NOME CARTA");
define("_TABLEECHARGERSTATUSTRANSACTIONS", "STATO E.CHARGER");
define("_TABLESTARTTRANSACTIONS", "TEMPO INIZIO");
define("_TABLEENDTRANSACTIONS", "TEMPO FINE");
define("_TABLECHARGINGTIMETRANSACTIONS", "TEMPO DI CARICA");
define("_TABLESUPPLIEDENERGYTRANSACTIONS", "ENERGIA EROGATA");
define("_TABLEERRORSTRANSACTIONS", "ERRORI");
define("_TABLENOTRANSACTIONTRANSACTIONS", "NESSUNA TRANSAZIONE TROVATA");
define("_TABLESTATUSREADYTRANSACTIONS", "PRONTO");
define("_TABLESTATUSCONNECTEDTRANSACTIONS", "CONNESSO");
define("_TABLESTATUSCHARGINGTRNSACTIONS", "IN CARICA");
define("_TABLESTATUSLOCKEDTRANSACTIONS", "LOCKED");
define("_TABLESTATUSERRORTRANSACTIONS", "ERRORE");
//commands.php
define("_TITLECOMMANDS", "DKC E.CHARGER | COMANDI");
define("_HEADCOMMANDS", "COMANDI");
define("_TABLEPARAMETERCOMMANDS", "PARAMETRO");
define("_TABLEVALUECOMMANDS", "VALORE / AZIONE");
define("_TABLEHELPCOMMANDS", "AIUTO");
define("_TABLE3000COMMANDS", "AZIONA E.CHARGER");
define("_TABLE3000SELCOMMANDS", "SELEZIONA");
define("_TABLE3000STARTCOMMANDS", "Start");
define("_TABLE3000STOPCOMMANDS", "Stop");
define("_TABLEAPPLYCOMMANDS", "APPLICA");
define("_TABLEINSERTVALUECOMMANDS", "INSERISCI UN VALORE");
define("_TABLE3003COMMANDS", "IMPOSTA POTENZA MASSIMA (W)");
define("_TABLE3006COMMANDS", "ABILITA MISURA PER LOAD BALANCING");
define("_TABLE3006SELCOMMANDS", "SELEZIONA");
define("_TABLE3006DISABLECOMMANDS", "DISATTIVA");
define("_TABLE3006ENABLECOMMANDS", "ATTIVA");
define("_TABLE3007COMMANDS", "LETTORE RFID");
define("_TABLE3007SELCOMMANDS", "SELEZIONA");
define("_TABLE3007DISABLECOMMANDS", "DISATTIVA");
define("_TABLE3007ENABLECOMMANDS", "ATTIVA");
define("_TABLE3009COMMANDS", "ATTIVA / DISATTIVA OCPP 1.6");
define("_TABLE3009SELCOMMANDS", "SELEZIONA");
define("_TABLE3009DISABLECOMMANDS", "DISATTIVA");
define("_TABLE3009ENABLECOMMANDS", "ATTIVA");
define("_TABLE3010COMMANDS", "ATTIVA / DISATTIVA MODBUS");
define("_TABLE3010SELCOMMANDS", "SELEZIONA");
define("_TABLE3010DISABLECOMMANDS", "DISATTIVA");
define("_TABLE3010ENABLECOMMANDS", "ATTIVA");
define("_TABLE3012COMMANDS", "AGGIORNAMENTO SOFTWARE");
define("_TABLE3013COMMANDS", "INVIO DATI E.CHARGER AL CLOUD");
define("_TABLE3014COMMANDS", "RESET ERRORI");
define("_TABLE3017COMMANDS", "RIAVVIO SISTEMA");
define("_TABLE3017SELCOMMANDS", "SELEZIONA");
define("_TABLE3017REBOOTCOMMANDS", "REBOOT");
define("_TABLE3017RESTARTCOMMANDS", "SOFT-RESTART");
define("_TOASTCOMMANDNOUPDATE", "NESSUN AGGIORNAMENTO DISPONIBILE");
define("_MODALSWUPDATECOMMANDS", "AGGIORNAMENTO SOFTWARE");
define("_MODALSWUPDATEWARNINGCOMMANDS", "SEI SICURO DI VOLER AGGIORNARE IL TUO E.CHARGER?");
define("_MODALNOCOMMANDS", "NO");
define("_MODALYESCOMMANDS", "SI");
define("_HELPOPERATECOMMANDS", "START / STOP CARICA");
define("_HELPMAXPOWERCOMMANDS", "IMPOSTA CARICO MASSIMO");
define("_HELPFIXEDPOWERCOMMANDS", "IMPOSTA POTENZA FISSA E DISATTIVA IL BILANCIAMENTO DINAMICO DEL POWER METER");
define("_HELPRFIDREADERCOMMANDS", "ATTIVA O DISATTIVA IL LETTORE RFID");
define("_HELPOCPPCOMMANDS", "ATTIVA O DISATTIVA IL PROTOCOLLO OCPP");
define("_HELPMODBUSCOMMANDS", "ATTIVA O DISATTIVA IL PROTOCOLLO MODBUS");
define("_HELPSWUPDATECOMMANDS", "AGGIORNA IL SOFTWARE DEL TUO E.CHARGER (CONNESSIONE AD INTERNET NECESSARIA)");
define("_HELPSENDCLOUDCOMMANDS", "AGGIORNA MANUALMENTE LE INFORMAZIONI IN CLOUD DEL TUO E.CHARGER");
define("_HELPERRORCOMMANDS", "RIPRISTINA LO STATO DEL TUO E.CHARGER");
define("_HELPREBOOT", "REBOOT=riavvia il tuo E.CHARGER | SOFT-RESTART=riavvia solo i servizi primari");
define("_ENABLED", "ABILITATO");
define("_DISABLED", "DISABILITATO");
define("_NOTAVAILABLE", "---");
define("_ENABLE", "ABILITA");
define("_DISABLE", "DISABILITA");
//configurations.php
define("_TITLECONFIGURATIONS", "DKC E.CHARGER | CONFIGURAZIONI");
define("_HEADCONFIGURATIONS", "CONFIGURAZIONI");
define("_TABLEUSER", "Parametri di configurazione utente");
define("_TABLEOCPP", "Parametri di configurazione comunicazione OCPP");
define("_TABLEINST", "Parametri di installazione");
define("_TABLENAMECONFIGURATIONS", "NOME");
define("_TABLEVALUECONFIGURATIONS", "VALORE");
define("_TABLEUOMCONFIGURATIONS", "UdM");
define("_TABLEMODIFYCONFIGURATIONS", "MODIFICA / AGGIORNA");
define("_TABLEHELPCONFIGURATIONS", "AIUTO");
define("_TABLESELCONFIGURATIONS", "SELEZIONA");
define("_TABLETRUECONFIGURATIONS", "VERO");
define("_TABLEFALSECONFIGURATIONS", "FALSO");
define("_TABLEITCONFIGURATIONS", "ITALIANO");
define("_TABLEENCONFIGURATIONS", "ENGLISH");
define("_TABLERUCONFIGURATIONS", "РУССКИЙ");
define("_TABLEUPDATECONFIGURATIONS", "AGGIORNA");
define("_TABLENOCONFIGURATIONS", "NESSUNA CONFIGURAZIONE TROVATA");
define("_TABLECONF1", "Potenza minima disponibile");
define("_TABLECONF2", "Timeout validita' carta RFID");
define("_TABLECONF3", "Pulsante premuto a lungo");
define("_TABLECONF4", "Pulsante premuto molto a lungo");
define("_TABLECONF5", "Corrente minima disponibile");
define("_TABLECONF6", "Nome produttore");
define("_TABLECONF7", "Indirizzo MODBUS");
define("_TABLECONF8", "Data di installazione");
define("_TABLECONF9", "Lingua");
define("_TABLECONF10", "Frequenza invio dati MQTT realtime al cloud");
define("_TABLECONF11", "Numero di serie");
define("_TABLECONF12", "Limite temperatura massima");
define("_TABLECONF13", "Limite temperatura minima");
define("_TABLECONF14", "Limite tensione minima");
define("_TABLECONF15", "Limite tensione massima");
define("_TABLECONF16", "Timeout connessione E.CHARGER");
define("_TABLECONF17", "Indirizzo IP server OCPP");
define("_TABLECONF18", "Porta server OCPP");
define("_TABLECONF19", "URL server OCPP");
define("_TABLECONF20", "Contatore interno di energia MID");
define("_TABLECONF21", "Presenza power meter esterno");
define("_TABLECONF22", "Presenza inverter");
define("_TABLECONF23", "Carica in pausa allo startup");
define("_TABLECONF24", "Intensita' luci LED");
define("_TABLECONF25", "Fuso orario");
define("_TABLECONF26", "Potenza massima casa");
define("_TABLECONF27", "MID Baudrate");
define("_TABLECONF28", "Storage Power Mode");
define("_TABLECONFGEN", "Parametro mancante");
//index_provisioning.php
define("_SELECTWIFINETWORK", "SCEGLI UNA RETE WIRELESS DISPONIBILE");
define("_FINDWIFINETWORK", "trova reti Wi-Fi disponibili");
