<?php
//RUSSIAN
//login.php
define("_TITLELOGIN", "DKC EOS Charge | Логин");
define("_HEADLOGIN", "DKC EOS Charge Логин");
define("_USERNAME", "Имя пользователя");
define("_PASSWORD", "Пароль");
define("_SUBMITLOGIN", "Логин");
define("_FORMMESSAGE1", "Пожалуйста, введите свое имя пользователя");
define("_FORMMESSAGE2", "Пожалуйста, введите свой пароль");
define("_FORMMESSAGE3", "Пожалуйста, проверьте свои учетные данные");
//change_password.php
define("_TITLECHANGEPASSWORD", "DKC EOS Charge | Изменить пароль");
define("_HEADCHANGEPASSWORD", "ИЗМЕНИТЬ ПАРОЛЬ ПРИ ПЕРВОМ ВХОДЕ В СИСТЕМУ");
define("_NEWPASSWORD1", "Новый пароль");
define("_NEWPASSWORD2", "Повторите новый пароль");
define("_NEWPASSWORDUPDATE", "Обновить");
define("_NEWPASSWORDMESSAGE1", "Введите новый пароль");
define("_NEWPASSWORDMESSAGE2", "Пароль должен содержать не менее 6 символов");
define("_NEWPASSWORDMESSAGE3", "Пароль должен отличаться от старого");
define("_NEWPASSWORDMESSAGE4", "Пожалуйста, подтвердите свой новый пароль");
define("_NEWPASSWORDMESSAGE5", "Пароли не совпадают");
//index_dashboard.php
define("_TITLESYSTEM", "DKC EOS Charge | ПАНЕЛЬ УПРАВЛЕНИЯ");
define("_MENUHOME", "ГЛАВНАЯ");
define("_MENULOGOUT", "ВЫЙТИ");
define("_MENUOVERVIEW", "ОБЗОР");
define("_MENUECHARGER", "EOS Charge");
define("_MENUTELEMETRY", "ТЕЛЕМЕТРИЯ");
define("_MENURFIDCARDS", "КАРТЫ RFID");
define("_MENUSTATISTICS", "СТАТИСТИКА");
define("_MENUTRANSACTIONS", "ТРАНЗАКЦИИ");
define("_MENUSETTINGS", "НАСТРОЙКИ");
define("_MENUCOMMANDS", "КОМАНДЫ");
define("_MENUCONFIGURATIONS", "КОНФИГУРАЦИИ");
define("_MENUERRORS", "ЖУРНАЛ ОШИБОК");
define("_MENUNETWORK", "СЕТЬ");
define("_MENUCLOSE", "ЗАКРЫТЬ");
define("_HEAD", "ПАНЕЛЬ УПРАВЛЕНИЯ");
define("_TABLEDATA", "ДАННЫЕ");
define("_TABLEVALUE", "ЗНАЧЕНИЕ");
define("_TABLEACTION", "ДЕЙСТВИЕ");
define("_TABLESERVERCOMM", "ДАТА");
define("_TABLEMACADDRESS", "MAC-адрес");
define("_TABLEMANUFACTURER", "ПРОИЗВОДИТЕЛЬ");
define("_TABLEMAXPOWER", "МАКСИМАЛЬНАЯ МОЩНОСТЬ EOS Charge");
define("_TABLEMODBUSADDRESS", "АДРЕС MODBUS");
define("_TABLELANIPADDRESS", "IP-АДРЕС LAN");
define("_TABLEWIFIPADDRESS", "IP-АДРЕС Wi-Fi");
define("_TABLELANGUAGE", "Язык");
define("_TABLEREALTIMESAMPLING", "ВЫБОРКА В РЕАЛЬНОМ ВРЕМЕНИ");
define("_TABLEWBTYPE", "ТИП EOS Charge");
define("_TABLESERIALNUMBER", "СЕРИЙНЫЙ НОМЕР");
define("_TABLEFWVERSION", "ВЕРСИЯ ПРОШИВКИ");
define("_TABLESWVERSION", "ВЕРСИЯ ПО");
define("_TABLERATEDPOWER", "НОМИНАЛЬНАЯ МОЩНОСТЬ");
define("_JAVASCRIPT0", "ОДНОФАЗНАЯ | КАБЕЛЬ");
define("_JAVASCRIPT1", "ТРЕХФАЗНАЯ | КАБЕЛЬ");
define("_JAVASCRIPT2", "ОДНОФАЗНАЯ | РАЗЕТКА");
define("_JAVASCRIPT3", "ТРЕХФАЗНАЯ | РАЗЕТКА");
define("_JAVASCRIPT4", "ОДНОФАЗНАЯ | КАБЕЛЬ | MID");
define("_JAVASCRIPT5", "ТРЕХФАЗНАЯ | КАБЕЛЬ | MID");
define("_JAVASCRIPT6", "ОДНОФАЗНАЯE | РАЗЕТКА | MID");
define("_JAVASCRIPT7", "ТРЕХФАЗНАЯ | РАЗЕТКА | MID");
define("_JAVASCRIPT8", "ОДНОФАЗНАЯ | КАБЕЛЬ | SIM");
define("_JAVASCRIPT9", "ТРЕХФАЗНАЯ | КАБЕЛЬ | SIM");
define("_JAVASCRIPT10", "ОДНОФАЗНАЯ | РАЗЕТКА | SIM");
define("_JAVASCRIPT11", "ТРЕХФАЗНАЯ | РАЗЕТКА | SIM");
define("_JAVASCRIPT12", "ОДНОФАЗНАЯ | КАБЕЛЬ | MID | SIM");
define("_JAVASCRIPT13", "ТРЕХФАЗНАЯ | КАБЕЛЬ | MID | SIM");
define("_JAVASCRIPT14", "ОДНОФАЗНАЯ | РАЗЕТКА | MID | SIM");
define("_JAVASCRIPT15", "ТРЕХФАЗНАЯ | РАЗЕТКА | MID | SIM");
//telemetry.php
define("_TITLETELEMETRY", "DKC EOS Charge | ТЕЛЕМЕТРИЯ");
define("_HEADTELEMETRY", "ТЕЛЕМЕТРИЯ");
define("_TABLEDATATELEMETRY", "ДАННЫЕ");
define("_TABLEVALUETELEMETRY", "ЗНАЧЕНИЕ");
define("_TABLEPOWERMETERTELEMETRY", "ИЗМЕРИТЕЛЬ МОЩНОСТИ");
define("_TABLEINSTANTPOWERTELEMETRY", "МГНОВЕННАЯ МОЩНОСТЬ");
define("_TABLERPHASECURRENTRTELEMETRY", "ТОК ФАЗЫ R");
define("_TABLESPHASECURRENTRTELEMETRY", "ТОК ФАЗЫ S");
define("_TABLETPHASECURRENTRTELEMETRY", "ТОК ФАЗЫ T");
define("_TABLEVOLTAGETELEMETRY", "НАПРЯЖЕНИЕ");
define("_TABLEACTIVEUSERTELEMETRY", "АКТИВНЫЙ ПОЛЬЗОВАТЕЛЬ");
define("_TABLEACTIVEUSERTELEMETRYNOBODY", "НИКТО");
define("_TABLECHARGINGTIMETELEMETRY", "ВРЕМЯ ЗАРЯДКИ");
define("_TABLESUPPLIEDENERGYTELEMETRY", "ПОДАВАЕМАЯ ЭНЕРГИЯ");
define("_TABLETEMPERATURETELEMETRY", "ТЕМПЕРАТУРА");
define("_TABLEECHARGERSTATUSTELEMETRY", "СТАТУС EOS Charge");
define("_ECHARGERSTATUSREADY", "ГОТОВА");
define("_ECHARGERSTATUSCONNECTED", "ПОДКЛЮЧЕН");
define("_ECHARGERSTATUSCHARGING", "ЗАРЯД");
define("_ECHARGERSTATUSLOCKED", "ЗАБЛОКИРОВАНО");
define("_ECHARGERSTATUSERROR", "ОШИБКА");
//cards.php
define("_TITLECARDS", "DKC EOS Charge | КАРТЫ RFID");
define("_HEADCARDS", "КАРТЫ RFID");
define("_ADDBUTTONHELPCARDS", "Нажмите и проведите RFID-карту");
define("_ADDBUTTONCARDS", "Добавить новую rfid-карту");
define("_TABLEIDCARDS", "ID");
define("_TABLERFIDCARDNOCARDS", "НОМЕР RFID-КАРТЫ");
define("_TABLECARDNAMECARDS", "НАЗВАНИЕ КАРТЫ");
define("_TABLECREATIONDATECARDS", "ДАТА СОЗДАНИЯ");
define("_TABLEFUNCTIONSCARDS", "ДЕЙСТВИЕ");
define("_TABLEBUTTONMODIFYNAMECARDS", "ИЗМЕНИТЬ ИМЯ КАРТЫ");
define("_TABLEBUTTONDELETECARDCARDS", "УДАЛИТЬ КАРТУ");
define("_TABLENOCARDSCARDS", "КАРТА НЕ НАЙДЕНА");
define("_MODALMODIFYNAMECARDS", "ИЗМЕНИТЬ ИМЯ КАРТЫ");
define("_MODALOLDNAMECARDS", "СТАРОЕ ИМЯ:");
define("_MODALNEWNAMECARDS", "НОВОЕ ИМЯ:");
define("_MODALOKCARDS", "OK");
define("_MODALDELETECARDCARDS", "Удалить карту");
define("_MODALDELETECARDWARNINGCARDS", "ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ УДАЛИТЬ ЭТУ RFID-КАРТУ??");
define("_MODALNOCARDS", "Нет");
define("_MODALYESCARDS", "Да");
define("_MODALTITLEMODIFYCARDCARDS", "Изменить имя для номера RFID-карты: ");
define("_MODALTITLEDELETECARDCARDS", "Удалить номер карты RIFD: ");
define("_TOASTCOMMANDKO", "ОШИБКА - КОМАНДА НЕ ВЫПОЛНЕНА");
define("_TOASTCOMMANDOK", "КОМАНДА ВЫПОЛНЕНА");
define("_TOASTCOMMANDNOTAVAILABLE", "КОМАНДА НЕДОСТУПНА");
define("_TOASTCOMMANDSKIPSERIAL", "КОМАНДА ВЫПОЛНЕНА");
define("_TOASTCOMMANDERROR", "ОШИБКА");
//transactions.php
define("_TITLETRANSACTIONS", "DKC EOS Charge | ТРАНЗАКЦИИ");
define("_HEADTRANSACTIONS", "ТРАНЗАКЦИИ");
define("_TABLEIDTRANSACTIONS", "ID");
define("_TABLEDATETRANSACTIONS", "ДАТА");
define("_TABLECARDNOTRANSACTIONS", "НОМЕР RFID-КАРТЫ");
define("_TABLECARDNAMETRANSACTIONS", "НАЗВАНИЕ КАРТЫ");
define("_TABLEECHARGERSTATUSTRANSACTIONS", "СТАТУС EOS Charge");
define("_TABLESTARTTRANSACTIONS", "ВРЕМЯ НАЧАЛА");
define("_TABLEENDTRANSACTIONS", "ВРЕМЯ ОКОНЧАНИЯ");
define("_TABLECHARGINGTIMETRANSACTIONS", "ВРЕМЯ ЗАРЯДКИ");
define("_TABLESUPPLIEDENERGYTRANSACTIONS", "ПОДАВАЕМАЯ ЭНЕРГИЯ");
define("_TABLEERRORSTRANSACTIONS", "ОШИБКИ");
define("_TABLENOTRANSACTIONTRANSACTIONS", "ТРАНЗАКЦИЯ НЕ НАЙДЕНА");
define("_TABLESTATUSREADYTRANSACTIONS", "ГОТОВ");
define("_TABLESTATUSCONNECTEDTRANSACTIONS", "ПОДКЛЮЧЕНО");
define("_TABLESTATUSCHARGINGTRNSACTIONS", "ЗАРЯД");
define("_TABLESTATUSLOCKEDTRANSACTIONS", "ЗАБЛОКИРОВАНО");
define("_TABLESTATUSERRORTRANSACTIONS", "ОШИБКА");
//commands.php
define("_TITLECOMMANDS", "DKC EOS Charge | КОМАНДЫ");
define("_HEADCOMMANDS", "КОМАНДЫ");
define("_TABLEPARAMETERCOMMANDS", "ПАРАМЕТР");
define("_TABLEVALUECOMMANDS", "ЗНАЧЕНИЕ / ДЕЙСТВИЕ");
define("_TABLEHELPCOMMANDS", "ПОМОЩЬ");
define("_TABLE3000COMMANDS", "УПРАВЛЯТЬ EOS Charge");
define("_TABLE3000SELCOMMANDS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLE3000STARTCOMMANDS", "Старт");
define("_TABLE3000STOPCOMMANDS", "Стоп");
define("_TABLEAPPLYCOMMANDS", "ПРИМЕНИТЬ");
define("_TABLEINSERTVALUECOMMANDS", "ПОЖАЛУЙСТА, ВВЕДИТЕ ЗНАЧЕНИЕ");
define("_TABLE3003COMMANDS", "УСТАНОВИТЬ МАКСИМАЛЬНУЮ МОЩНОСТЬ (W)");
define("_TABLE3006COMMANDS", "ЛОКАЛЬНАЯ ДИНАМИЧЕСКАЯ БАЛАНСИРОВКА");
define("_TABLE3006SELCOMMANDS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLE3006DISABLECOMMANDS", "ВЫКЛЮЧИТЬ");
define("_TABLE3006ENABLECOMMANDS", "ВКЛЮЧИТЬ");
define("_TABLE3007COMMANDS", "СЧИТЫВАТЕЛЬ RFID-КАРТ");
define("_TABLE3007SELCOMMANDS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLE3007DISABLECOMMANDS", "ВЫКЛЮЧИТЬ");
define("_TABLE3007ENABLECOMMANDS", "ВКЛЮЧИТЬ");
define("_TABLE3009COMMANDS", "ВКЛЮЧИТЬ / ВЫКЛЮЧИТЬ OCPP 1.6");
define("_TABLE3009SELCOMMANDS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLE3009DISABLECOMMANDS", "ВЫКЛЮЧИТЬ");
define("_TABLE3009ENABLECOMMANDS", "ВКЛЮЧИТЬ");
define("_TABLE3010COMMANDS", "ВКЛЮЧИТЬ / ВЫКЛЮЧИТЬ MODBUS");
define("_TABLE3010SELCOMMANDS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLE3010DISABLECOMMANDS", "ВЫКЛЮЧИТЬ");
define("_TABLE3010ENABLECOMMANDS", "ВКЛЮЧИТЬ");
define("_TABLE3012COMMANDS", "ОБНОВЛЕНИЕ ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ");
define("_TABLE3013COMMANDS", "ОТПРАВИТЬ ДАННЫЕ EOS Charge В ОБЛАКО");
define("_TABLE3014COMMANDS", "СБРОС ОШИБОК");
define("_TABLE3017COMMANDS", "ПЕРЕЗАГРУЗКА СИСТЕМЫ");
define("_TABLE3017SELCOMMANDS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLE3017REBOOTCOMMANDS", "REBOOT");
define("_TABLE3017RESTARTCOMMANDS", "SOFT-RESTART");
define("_TOASTCOMMANDNOUPDATE", "НЕТ ДОСТУПНЫХ ОБНОВЛЕНИЙ");
define("_MODALSWUPDATECOMMANDS", "ОБНОВЛЕНИЕ ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ");
define("_MODALSWUPDATEWARNINGCOMMANDS", "ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ ОБНОВИТЬ СВОЙ EOS Charge?");
define("_MODALNOCOMMANDS", "Нет");
define("_MODALYESCOMMANDS", "Да");
define("_TITLEREBOOT", "DKC E.CHARGER | REBOOTING");
define("_REBOOTING", "ОБНОВЛЕНИЕ EOS CHARGE");
define("_REBOOTINGMESSAGE1", "Обновлегие…");
define("_REBOOTINGMESSAGE2", "Пожалуйста, подождите, ваш EOS Charge обновляется");
define("_REBOOTINGMESSAGE5", "Он перезапустится после завершения");
define("_HELPOPERATECOMMANDS", "СТАРТ / СТОП ЗАРЯД");
define("_HELPMAXPOWERCOMMANDS", "Установите максимальную нагрузку");
define("_HELPFIXEDPOWERCOMMANDS", "Установите режим фиксированного питания и отключите динамическое управление счетчиком мощности");
define("_HELPRFIDREADERCOMMANDS", "ВКЛЮЧИТЬ / ВЫКЛЮЧИТЬ считыватель rfid-карт");
define("_HELPOCPPCOMMANDS", "ВКЛЮЧИТЬ / ВЫКЛЮЧИТЬ OCPP");
define("_HELPMODBUSCOMMANDS", "ВКЛЮЧИТЬ / ВЫКЛЮЧИТЬ MODBUS");
define("_HELPSWUPDATECOMMANDS", "Обновить ПО EOS Charge (ТРЕБУЕТСЯ ПОДКЛЮЧЕНИЕ К ИНТЕРНЕТУ");
define("_HELPSENDCLOUDCOMMANDS", "Обновить облако информацией об EOS Charge ВРУЧНУЮ");
define("_HELPERRORCOMMANDS", "Восстановить статус EOS Charge");
define("_HELPREBOOT", "REBOOT = Перезагрузить EOS Charge | SOFT-RESTART = Перезагрузите только основные службы");
define("_ENABLED", "ВКЛЮЧЕНO");
define("_DISABLED", "ВЫКЛЮЧЕНО");
define("_NOTAVAILABLE", "---");
define("_ENABLE", "ВКЛЮЧИТЬ");
define("_DISABLE", "ВЫКЛЮЧИТЬ");
//configurations.php
define("_TITLECONFIGURATIONS", "DKC EOS Charge | КОНФИГУРАЦИИ");
define("_HEADCONFIGURATIONS", "КОНФИГУРАЦИИ");
define("_TABLEUSER", "Параметры конфигурации пользователя");
define("_TABLEOCPP", "Параметры конфигурации связи OCPP");
define("_TABLEINST", "Параметры установки");
define("_TABLENAMECONFIGURATIONS", "ИМЯ");
define("_TABLEVALUECONFIGURATIONS", "ЗНАЧЕНИЕ");
define("_TABLEUOMCONFIGURATIONS", "UoM");
define("_TABLEMODIFYCONFIGURATIONS", "МОДИФИЦИРОВАТЬ / ОБНОВИТЬ");
define("_TABLEHELPCONFIGURATIONS", "ПОМОЩЬ");
define("_TABLESELCONFIGURATIONS", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ");
define("_TABLETRUECONFIGURATIONS", "ВЕРНО");
define("_TABLEFALSECONFIGURATIONS", "НЕВЕРНО");
define("_TABLEITCONFIGURATIONS", "ITALIANO");
define("_TABLEENCONFIGURATIONS", "ENGLISH");
define("_TABLERUCONFIGURATIONS", "РУССКИЙ");
define("_TABLEUPDATECONFIGURATIONS", "ОБНОВИТЬ");
define("_TABLENOCONFIGURATIONS", "КОНФИГУРАЦИЯ НЕ НАЙДЕНА");
define("_TABLECONF1", "Минимальная доступная мощность");
define("_TABLECONF2", "Тайм-аут действия RFID");
define("_TABLECONF3", "Долгое нажатие кнопки");
define("_TABLECONF4", "Очень долгое нажатие кнопки");
define("_TABLECONF5", "Минимальный доступный ток");
define("_TABLECONF6", "Название производителя");
define("_TABLECONF7", "Адрес MODBUS");
define("_TABLECONF8", "Дата активации");
define("_TABLECONF9", "Язык");
define("_TABLECONF10", "Время между опросом данных MQTT");
define("_TABLECONF11", "Серийный номер Wallbox");
define("_TABLECONF12", "Максимальный температурный предел");
define("_TABLECONF13", "Минимальный температурный предел");
define("_TABLECONF14", "Минимальный предел напряжения");
define("_TABLECONF15", "Максимальный предел напряжения");
define("_TABLECONF16", "Время ожидания соединения EOS Charge");
define("_TABLECONF17", "IP-адрес сервера OCPP");
define("_TABLECONF18", "Порт сервера OCPP");
define("_TABLECONF19", "URL-адрес сервера OCPP");
define("_TABLECONF20", "Внутренний измеритель мощности");
define("_TABLECONF21", "Внешний измеритель мощности");
define("_TABLECONF22", "Наличие инвертора");
define("_TABLECONF23", "Приостановка зарядки при запуске");
define("_TABLECONF24", "Интенсивность светодиодов");
define("_TABLECONF25", "Часовой пояс");
define("_TABLECONF26", "Максимальная домашняя мощность");
define("_TABLECONFGEN", "Параметр отсутствует");
//errors.php
define("_TITLEERRORS", "DKC EOS Charge | ЖУРНАЛ ОШИБОК");
define("_HEADERRORS", "ЖУРНАЛ ОШИБОК");
define("_FILTERSEL", "ФИЛЬТР ПАРАМЕТРОВ");
define("_FILTERSELINFO", "ИНФО");
define("_FILTERSELERROR", "ОЩИБКА");
define("_FILTERSELWARNING", "ПРЕДУПРЕЖДЕНИЕ");
define("_FILTERSELALL", "ВСЕ");
define("_TABLEIDERRORS", "ID");
define("_TABLEDATEERRORS", "ДАТА");
define("_TABLEVALUEERRORS", "ЗНАЧЕНИЕ");
define("_TABLESEVERITYERRORS", "ВАЖНОСТЬ");
define("_TABLEPARAMETERERRORS", "ПАРАМЕТР");
define("_TABLENOERRORS", "ОШИБКА НЕ НАЙДЕНА");
//index_provisioning.php
define("_SELECTWIFINETWORK", "ПОЖАЛУЙСТА, ВЫБЕРИТЕ БЕСПРОВОДНУЮ СЕТЬ");
define("_FINDWIFINETWORK", "Найти доступные беспроводные сети");
//network.php
define("_TITLENETWORK", "DKC EOS Charge | СЕТЕВЫЕ НАСТРОЙКИ");
define("_HEADNETWORK", "СЕТЕВЫЕ НАСТРОЙКИ");
define("_TITLENETWORKREBOOT", "DKC EOS Charge | ПЕРЕЗАГРУЗКА");
define("_NETWORKREBOOTING", "ПЕРЕЗАГРУЗКА EOS Charge");
define("_NETWORKREBOOTINGMESSAGE1", "Перезагрузка...");
define("_NETWORKREBOOTINGMESSAGE2", "Если вы изменили параметры сети, пожалуйста, перейдите по новому адресу через строку браузера, чтобы заново найти EOS Charge");
define("_NETWORKREBOOTINGMESSAGE3", "Зарегистрируйтесь на нашей платформе для получения всех дополнительных услуг");
define("_NETWORKREBOOTINGMESSAGE4", "Когда светодиодная полоса станет зелёной, ваш EOS Charge будет сново готов");
define("_NETWORKREBOOTINGMESSAGE5", "Вы можете закрыть это окно");
define("_PROVISIONINGWIFI", "БЕСПРОВОДНАЯ СЕТЬ");
define("_PROVISIONINGSSIDNAME", "Имя SSID");
define("_PROVISIONINGPASSWORD", "Пароль");
define("_PROVISIONINGWIFIDHCP", "Беспроводная сеть DHCP");
define("_PROVISIONINGWIFISTATICIP", "Статический IP ADDRESS беспроводной сети");
define("_PROVISIONINGWIFINETMASK", "NETMASK беспроводной сети");
define("_PROVISIONINGWIFIGATEWAY", "GATEWAY беспроводной сети");
define("_PROVISIONINGWIFIDNS", "DNS беспроводной сети");
define("_PROVISIONINGNETWORK", "СЕТЬ LAN");
define("_PROVISIONINGNETWORKDHCP", "DHCP");
define("_PROVISIONINGNETWORKSTATICIP", "Статический IP-АДРЕС сети LAN");
define("_PROVISIONINGNETWORKNETMASK", "NETMASK локальной сети");
define("_PROVISIONINGNETWORKGATEWAY", "GATEWAY локальной сети");
define("_PROVISIONINGNETWORKDNS", "DNS локальной сети");
define("_PROVISIONINGAPPLY", "ПРИМЕНИТЬ");
define("_PROVISIONINGNONETWORK", "ПРОДОЛЖИТЬ БЕЗ СЕТИ");
define("_MODALNETWORK", "ПРОДОЛЖИТЬ БЕЗ СЕТИ");
define("_MODALWARNING", "ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ ПРОДОЛЖИТЬ БЕЗ СЕТИ?");
define("_MODALMESSAGEROW1", "--- ПРЕДУПРЕЖДЕНИЕ ---");
define("_MODALMESSAGEROW2", "--- EOS Charge ПЕРЕЗАГРУЗИТСЯ ---");
define("_MODALNO", "НЕТ");
define("_MODALYES", "ДА");
define("_MODALMISSINGDATA", "ОТСУТСТВУЮЩИЕ ДАННЫЕ");
define("_MODALMISSINGDATAMESSAGE", "ПОЖАЛУЙСТА, ЗАПОЛНИТЕ ВСЕ ОБЯЗАТЕЛЬНЫЕ ПОЛЯ!");
